services:
  youtube_explorer:
    build:
      context: docker
    container_name: youtube_explorer
    volumes:
      - './www:/var/www'
      - '/var/www/docker'
    ports:
      - '2050:80'
    working_dir: /var/www
  youtube_explorer_db:
    image: 'mysql:latest'
    container_name: youtube_explorer_db
    environment:
      - MYSQL_ROOT_PASSWORD=myverystrongpassword
    ports:
      - '3400:3306'
