# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    google_cloud_api_key: '%env(GOOGLE_CLOUD_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        # resource: '../tests/ServicesTest/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Services\MassFetchManager:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Services\FetchAllVideos:
        arguments:
            $apiKey: '%env(GOOGLE_CLOUD_API_KEY)%'
            $httpClient: '@web_client.client'
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@logger'
            $massFetchManager: '@App\Services\MassFetchManager'

    App\MessageHandler\FetchAllVideosFromYoutubeChannelHandler:
        arguments:
            $channelRepository: '@App\Repository\ChannelRepository'
            $fetchAllVideos: '@App\Services\FetchAllVideos'
            $apiKey: '%env(GOOGLE_CLOUD_API_KEY)%'
            $httpClient: '@web_client.client'

    App\Services\Fetch:
        arguments:
            $apiKey: '%env(GOOGLE_CLOUD_API_KEY)%'
            $httpClient: '@web_client.client'

    guzzle_http.client:
        class: GuzzleHttp\Client

    web_client.client:
        class: App\Services\WebClient
        arguments:
            $client: '@guzzle_http.client'
            $logger: '@logger'

    mass_fetch_iteration_repository:
        class: App\Repository\MassFetchIterationRepository
        public: true

when@test:
    services:
        guzzle_http.client:
            class: App\Tests\Mocks\ClientMock

        logger.mock:
            class: App\Tests\ServicesTest\LoggerMock
            public: true

        # web_client.client:
        #     class: App\Tests\Mocks\Services\WebClientMock
            # arguments:
            #     $client: '@guzzle_http.client'
            #     $logger: '@logger.mock'
    


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
